from typing import TypedDict, List, Dict, Any, Optional

class BlogState(TypedDict):
    """
    The shared data container. All pipeline nodes read from and write to this object.
    The state flows from node to node carrying all information.
    """
    run_id: str
    topic: str
    mode: Optional[str]                     # closed_book, hybrid, open_book
    needs_research: Optional[bool]          # True if mode is hybrid or open_book
    evidence: Optional[List[Dict[str, Any]]] # Research facts gathered from Tavily
    plan: Optional[Dict[str, Any]]          # The JSON structure generated by Gemini
    pending_task_count: Optional[int]       # Number of sections pushed to Kafka
    merged_content: Optional[str]           # The final assembled Markdown
    image_prompts: Optional[List[Dict[str, Any]]]
    md_file_path: Optional[str]             # Where the file is saved (S3 or local)